In [1]:
import tensorflow as tf
import numpy as np

# y= relu ( (X․W ) + b )

In [2]:
X = tf.Variable([[0.4,0.2,0.4]])

W = tf.Variable([[-0.5,-0.2 ],
                 [-0.3, 0.4 ],
                 [-0.5, 0.2 ]])
                         
b = tf.Variable([[0.1,0.2]])
    
XWb =tf.matmul(X,W)+b

y=tf.nn.relu(tf.matmul(X,W)+b)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')    
    print(sess.run(XWb ))    
    print('y:')    
    print(sess.run(y ))

Instructions for updating:
Colocations handled automatically by placer.
XWb:
[[-0.36000004  0.28      ]]
y:
[[-0.    0.28]]


# y= sigmoid ( (X․W ) + b )

In [3]:
X = tf.Variable([[0.4,0.2,0.4]])

W = tf.Variable([[-0.5,-0.2 ],
                 [-0.3, 0.4 ],
                 [-0.5, 0.2 ]])

b = tf.Variable([[0.1,0.2]])

XWb=tf.matmul(X,W)+b

y=tf.nn.sigmoid(tf.matmul(X,W)+b)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')    
    print(sess.run(XWb))    
    print('y:')    
    print(sess.run(y ))

XWb:
[[-0.36000004  0.28      ]]
y:
[[0.41095954 0.5695462 ]]


# 以亂數產生Weight(W)與bais(b) 

In [4]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
X = tf.Variable([[0.4,0.2,0.4]])
y=tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('b:')
    print(sess.run(b ))    
    print('W:')
    print(sess.run(W ))
    print('y:')
    print(sess.run(y ))    

b:
[[-0.45671737  1.9184296 ]]
W:
[[ 1.7578148   1.0365098 ]
 [-1.3721542   0.17948511]
 [-1.250039    0.01544663]]
y:
[[-0.         2.3751092]]


In [5]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
X = tf.Variable([[0.4,0.2,0.4]])
y=tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    (_b,_W,_y)=sess.run((b,W,y))
    print('b:')
    print(_b)
    print('W:')
    print(_W)
    print('y:')
    print(_y)   

b:
[[ 0.15169111 -0.3762241 ]]
W:
[[-0.03389708  2.079205  ]
 [ 1.1108719  -1.6277827 ]
 [-1.2262421  -0.897338  ]]
y:
[[-0. -0.]]


# placeholder

In [6]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
X = tf.placeholder("float", [None,3])
y=tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2,0.4]])
    (_b,_W,_X,_y)=sess.run((b,W,X,y),feed_dict={X:X_array})
    print('b:')
    print(_b)    
    print('W:')
    print(_W)
    print('X:')
    print(_X)
    print('y:')
    print(_y)

b:
[[-1.1712605 -0.8339476]]
W:
[[-0.40144497 -1.5033574 ]
 [-0.8127115  -0.12607491]
 [ 1.211768   -0.8862347 ]]
X:
[[0.4 0.2 0.4]]
y:
[[-0. -0.]]


In [7]:
_y.shape

(1, 2)

In [8]:
ts_norm = tf.random_normal([1000])
with tf.Session() as session:
    norm_data=ts_norm.eval()
print(len(norm_data))
print(norm_data[:30])

1000
[ 0.62225825  0.29151925  1.0019113   0.5351777  -0.85592717  0.17916904
  3.5333905   2.1766493   0.7742961   1.6985333   1.0108353   0.08293124
  1.0464045  -1.1610093   0.5783422  -1.1384286   0.4055195   0.19288734
 -1.0875244   1.2783896   1.1132098   0.04432624 -1.6961008  -0.6690534
  1.2609922   0.16882353  0.619171    0.06678982  0.77180165 -0.49760395]


In [9]:
import matplotlib.pyplot as plt
plt.hist(norm_data)
plt.show()    

<Figure size 640x480 with 1 Axes>

In [10]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
X = tf.placeholder("float", [None,3])
y=tf.nn.sigmoid(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2 ,0.4],
                        [0.3,0.4 ,0.5],
                        [0.3,-0.4,0.5]])    
    (_b,_W,_X,_y)=sess.run((b,W,X,y),feed_dict={X:X_array})
    print('b:')
    print(_b)    
    print('W:')
    print(_W)
    print('X:')
    print(_X)
    print('y:')
    print(_y)

b:
[[ 0.669695  -1.1147591]]
W:
[[ 0.70771325  0.36250317]
 [ 0.3185764  -0.17253125]
 [-0.3363256   0.76930326]]
X:
[[ 0.4  0.2  0.4]
 [ 0.3  0.4  0.5]
 [ 0.3 -0.4  0.5]]
y:
[[0.7072293  0.3325792 ]
 [0.69873405 0.333951  ]
 [0.6425423  0.36532077]]


In [11]:
def layer(output_dim,input_dim,inputs, activation=None):
    W = tf.Variable(tf.random_normal([input_dim, output_dim]))
    b = tf.Variable(tf.random_normal([1, output_dim]))
    XWb = tf.matmul(inputs, W) + b
    if activation is None:
        outputs = XWb
    else:
        outputs = activation(XWb)
    return outputs

In [12]:
X = tf.placeholder("float", [None,4])

y=layer(output_dim=3,input_dim=4,inputs=X,
        activation=tf.nn.relu)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2 ,0.4,0.1],
                        [0.3,0.4 ,0.5,0.3],
                        [0.3,-0.4,0.5,0.2]])    
    (_X,_y)=sess.run((X,y),feed_dict={X:X_array})
    print('X:')
    print(_X)
    print('y:')
    print(_y)    

X:
[[ 0.4  0.2  0.4  0.1]
 [ 0.3  0.4  0.5  0.3]
 [ 0.3 -0.4  0.5  0.2]]
y:
[[-0.          1.5779527   0.08151242]
 [-0.          1.8443446   0.34151635]
 [ 0.44860858  1.3648791   0.01903495]]


In [13]:
X = tf.placeholder("float", [None,4])
h=layer(output_dim=3,input_dim=4,inputs=X,
        activation=tf.nn.relu)
y=layer(output_dim=2,input_dim=3,inputs=h)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2 ,0.4,0.5]])    
    (layer_X,layer_h,layer_y)= \
            sess.run((X,h,y),feed_dict={X:X_array})
    print('input Layer X:')
    print(layer_X)
    print('hidden Layer h:')
    print(layer_h)
    print('output Layer y:')
    print(layer_y)

input Layer X:
[[0.4 0.2 0.4 0.5]]
hidden Layer h:
[[-0.         0.0720752 -0.       ]]
output Layer y:
[[-0.6806876 -1.4827732]]


In [14]:
def layer_debug(output_dim,input_dim,inputs, activation=None):
    W = tf.Variable(tf.random_normal([input_dim, output_dim]))
    b = tf.Variable(tf.random_normal([1, output_dim]))
    XWb = tf.matmul(inputs, W) + b
    if activation is None:
        outputs = XWb
    else:
        outputs = activation(XWb)
    return outputs,W,b

In [15]:
X = tf.placeholder("float", [None,4])
h,W1,b1=layer_debug(output_dim=3,input_dim=4,inputs=X,
                    activation=tf.nn.relu)
y,W2,b2=layer_debug(output_dim=2,input_dim=3,inputs=h)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2 ,0.4,0.5]])    
    (layer_X,layer_h,layer_y,W1,b1,W2,b2)= \
             sess.run((X,h,y,W1,b1,W2,b2),feed_dict={X:X_array})
    print('input Layer X:')
    print(layer_X)
    print('W1:')
    print(  W1)    
    print('b1:')
    print(  b1)    
    print('hidden Layer h:')
    print(layer_h)    
    print('W2:')
    print(  W2)    
    print('b2:')
    print(  b2)    
    print('output Layer y:')
    print(layer_y)

input Layer X:
[[0.4 0.2 0.4 0.5]]
W1:
[[-1.3205608  -1.0819418   0.72290295]
 [ 1.1828423  -0.23469314 -0.34072897]
 [-0.14606291  1.4003227   1.7174944 ]
 [-0.30815995 -0.8048944   1.5749421 ]]
b1:
[[ 0.71511215 -0.4771474   0.46181974]]
hidden Layer h:
[[ 0.21095115 -0.          2.1573038 ]]
W2:
[[-3.039205    0.60372376]
 [-0.7558675  -0.80065584]
 [ 0.2029641  -0.0574487 ]]
b2:
[[1.4001986  0.49502093]]
output Layer y:
[[1.1969299  0.49844283]]
